### ISSUE TITLE
(Windows) Library loading fails with 'Unspecified error'

### ISSUE THREAD

**Issue by tridius** [hansihe/rustler#100]
I am trying to implement a very simple NIF using the default "add" function generated by `mix rustler.new`. The project compiles and can be run on OSX, but when I try to build the same project on Windows, I get the following error:

```
mix compile
Compiling NIF crate :rust_lib (native/rust_lib)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Compiling 1 file (.ex)

== Compilation error on file lib/testing.ex ==

15:00:16.527 [warn]  The on_load function for module Elixir.ElixirCode returned {:error,
 {:load_failed,
  'Failed to load NIF library c:/Users/NCoish/Desktop/testing/_build/dev/lib/testing/priv/native/librust_lib: \'Unspecified error\''}}

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

The `librust_lib` that it's looking for exists at that filepath as `librust_lib.dll` on Windows.

The lib file looks like this:

```
#[macro_use] extern crate rustler;
#[macro_use] extern crate rustler_codegen;
#[macro_use] extern crate lazy_static;

use rustler::{NifEnv, NifTerm, NifResult, NifEncoder};

mod atoms {
    rustler_atoms! {
        atom ok;
        //atom error;
        //atom __true__ = "true";
        //atom __false__ = "false";
    }
}

rustler_export_nifs! {
    "Elixir.ElixirCode",
    [("add", 2, add)],
    None
}

fn add<'a>(env: NifEnv<'a>, args: &[NifTerm<'a>]) -> NifResult<NifTerm<'a>> {
    let num1: i64 = try!(args[0].decode());
    let num2: i64 = try!(args[1].decode());

    Ok((atoms::ok(), num1 + num2).encode(env))
}
```
The reason I suspect this as a bug is that it builds correctly on OSX and the functions can be called through iex. Please let me know if you would like me to provide more details.

System configuration:
Windows 10
rustc 1.17.0 (56124baa9 2017-04-24) (stable)
Elixir 1.4.2
Rustler: {:rustler, github: "hansihe/rustler", sparse: "rustler_mix", branch: "master"}

**Comment by hansihe** [comment]
I don't know what could cause this. I think I'm gonna have to try getting my hand on a windows installation to try reproducing it on.

Could it be the same/related to [this](https://github.com/riverrun/comeonin/issues/39) issue?

**Comment by tridius** [comment]
Interesting, that issue is worth looking in to. I'll have access to the system I was trying to build on again on Monday; I'll check this out first thing Monday morning!

Interestingly, I tried building on another Windows machine yesterday, and I can actually get the application to compile correctly. Unfortunately a completely different error happens in this case: When I try to build with `iex -S mix` everything builds correctly, but when I try to make a call to the `ElixirCode.add` function, iex crashes completely with an "Illegal instruction" error. This also happens if I try to call the code from within a module (i.e. Not just from within iex). I think this is a completely different issue however.

**Comment by tridius** [comment]
Quick Update: I was right, it was something with my environment. I was dumb and forgot that I was using Rust stable-i686-pc-windows-msvc for a separate 32-bit application I was building, and that was set as my default Rust. As soon as I switched over to stable-x86_64-pc-windows-msvc the build succeeded as it did on my second Windows machine.

Maybe it would be worthwhile to note that only x86_64 is currently supported on Windows?

After the build succeeds I'm still getting the Illegal Instruction error I noted above however. Should I create a separate issue?

**Comment by tridius** [comment]
After doing a little more digging, it seems I can enter the rust function call. The following is the function I'm trying to call:

```
fn add<'a>(env: NifEnv<'a>, args: &[NifTerm<'a>]) -> NifResult<NifTerm<'a>> {
    println!("Hello");
    let num1: i64 = try!(args[0].decode());
    println!("Hello again!");
    let num2: i64 = try!(args[1].decode());
    println!("Goodbye");

    Ok((atoms::ok(), num1 + num2).encode(env))
}
```
The prints are just for debugging, it turns out that "Hello" gets printed successfully, so the call that seems to be causing the illegal instruction crash is `let num1: i64 = try!(args[0].decode());`

**Comment by hansihe** [comment]
Glad you worked the first issue out!

It might be better to have a separate issue for the other issue.
