### ISSUE TITLE
Exposing `enif_schedule_nif`

### ISSUE THREAD

**Issue by Qqwy** [hansihe/rustler#106]
As stated in [issue #44's discussion](https://github.com/hansihe/Rustler/issues/44#issuecomment-269916075), `enif_schedule_nif` is currently not exposed by Rustler because it is not known how to expose the function in a compile-time safe way,

as the NIF is supposed to return to the Erlang scheduler right after `enif_schedule_nif` was called.

My proposal would be to expose `enif_schedule_nif` in an `unsafe` context, to ensure that people that want to use it are mindful of if they are using it in the proper way.

In the future, it might be possible to wrap `enif_schedule_nif` in some way.
An example would be as a preemptive Iterator-consumer, to ensure that the NIF will be split in chunks of `O(1)`, even when performing `O(n)` or `O(n^2)` etc iterations.

**Comment by hansihe** [comment]
I totally agree with this, if there is an API we can't expose safely, we should do it unsafely with warnings.

If you want to give this a go, I would be fully open to pull requests. I might give it a go next week after I am done with my talk at PolyConf.

**Comment by hansihe** [comment]
Closing this issue in favour of https://github.com/hansihe/rustler/issues/107, it contains more discussion
