### ISSUE TITLE
Erlang/Elixir

### ISSUE THREAD

**Issue by ShalokShalom** [hansihe/rustler#110]
The top decription here says 'Erlang' while Elixir is now prefered.

**Comment by treyzania** [comment]
Elixir can "seamlessly" call Erlang functions, so it's more accurate to say Erlang as you can still use Rustler for Erlang code, even if you're transitively using Elixir somewhere in there.

**Comment by ShalokShalom** [comment]
I mean that the description text and the text in the README bite each other. 
Plus, its not clear that Elixir is supported, reading the description line.
