### ISSUE TITLE
Storing monitor references in resources

### ISSUE THREAD

**Issue by evnu** [hansihe/rustler#117]
I would like to store a monitor reference within a resource, but could not find a way to do this with rustler 0.15.1. To illustrate what I mean, I would like to pass a reference generated with `Process.monitor/1` into Rust. For example, I'd like to pass it through a roundtrip function and maybe store it in a resource:

```rust
pub fn roundtrip<'a>(env: NifEnv<'a>, args: &[NifTerm<'a>]) -> NifResult<NifTerm<'a>> {
  let monitor : NifMonitorRef = args[0].decode?();
  // maybe store it some place safe
  Ok(monitor.encode())
}
```

Did I miss something obvious on how to handle monitor references with rustler? I tried to avoid decoding the reference altogether by saving a `NifTerm` in a resource, but that did not work out in the end due to lifetime issues (I could not pass a lifetime for the resource into the `resource_struct_init!()` macro).

**Comment by hansihe** [comment]
As far as I can see, there are no functions in the Erlang NIF api for encoding/decoding references from terms, so I don't think there is a lot we can do here.

One alternative would be to use `enif_term_to_binary` to obtain a binary version of the reference, then storing that in a type, but this is certainly a hack, and I would like to avoid it.

**Comment by hansihe** [comment]
To be clear, I would like to avoid adding it to rustler itself.

You could do it yourself, do `ref.to_binary()` to obtain a [External Term Format](http://erlang.org/doc/apps/erts/erl_ext_dist.html#id100739) encoded version of the reference. You could then store that  wherever you like, then convert it back into a term when you would like to use it again.

Again, this is a hack, but it's the best way I can think of doing this with the current API.

**Comment by evnu** [comment]
Yes, encoding it in external format makes sense, thanks for pointing me into that direction. I guessed that there should be a "proper" way to represent references, because erlang_nif-sys implements an `ErlNifMonitor` [here](https://github.com/goertzenator/erlang_nif-sys/blob/master/src/erlang_nif_sys_api.rs), but this probably uses the internal representation from OTP directly.
