### ISSUE TITLE
Running `mix test` does not work on the first run (needs to compile twice)

### ISSUE THREAD

**Issue by rafapaez** [hansihe/rustler#123]
```
[Modify the `mix.exs` file]

$ mix test
Compiling NIF crate :rustler_test (native/rustler_test)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Compiling 221 files (.ex)

13:15:37.820 [warn]  The on_load function for module Elixir.RustlerTest returned:
{:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}

[Tests fail]

[Then, running again works]

$ mix test

[Tests succeed]
```

To make it work in travis CI I had to compile before running the tests:

```
 - MIX_ENV=test mix compile
 - mix test || travis_terminate 1
```

Same issue happens when trying to open the console with: `iex -S mix`

Rustler compiler is in the recommended order:
`compilers: [:rustler, :phoenix, :gettext] ++ Mix.compilers,`

**Comment by scrogson** [comment]
@rafapaez yes, @hansihe and I have noticed this happening. The issue is that the `priv` directory needs to exist before `mix compile` will properly symlink it to the `_build` directory. The way I've gotten around this is by committing a `priv/.keep` so that the `priv` dir always exists.

**Comment by rafapaez** [comment]
Thanks @scrogson . I've tried adding a `priv/.keep` but it still fails. I just need to modify the `mix.exs` and run `mix test` to reproduce it in my local computer. What am I missing?

**Comment by scohen** [comment]
@scrogson I'm in the same boat, tried the `.keep` hack and it still fails. Any suggestions? Can I give you some additional info?

**Comment by scrogson** [comment]
Just noticed that I said `priv/.keep` but it most likely should have been `priv/native/.gitkeep`. I am not running into this issue on either Linux or MacOS with this in place.

**Comment by scrogson** [comment]
Hmmm...nope...I guess I was correct the first time: https://github.com/hansihe/rustler/tree/master/rustler_tests/priv

@scohen can you share versions? OS and Rustler?

**Comment by scohen** [comment]
@scrogson I sure can. I'm running:
OS: OSX mojave and Ubuntu 18.10. Elixir
Rustler: 0.18.0
Elixir: 1.7.4
Erlang: 21.1

The easiest test case I came up with is:
```
code - master! ❯ touch mix.exs
code - master! ❯ mix compile
Compiling NIF crate :column_store (native/column_store)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
Compiling 47 files (.ex)

20:34:12.608 [warn]  The on_load function for module Elixir.ColumnStore.FrozenColumn returned:
{:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}


== Compilation error in file lib/column_store/column.ex ==
** (CompileError) lib/column_store/column.ex:4: module ColumnStore.FrozenColumn is not loaded and could not be found
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by scohen** [comment]
To be clear, I've put `.keep` and `.gitkeep` in 
<PROJECT_ROOT>/priv/.gitkeep

**Comment by pguillory** [comment]
Been looking at this off and on for that last few days as well. Another way to trigger the bug, this fails with "upgrade not supported" every *other* time you run it:
```
touch mix.exs && mix compile
```
Seems like what's happening is if the `.beam` file for our NIF-backed Elixir module exists under _build, it gets loaded at startup and calls its `@on_load`, which calls `:erlang.load_nif`. Then Elixir recompiles the module and calls `:code.load` to bring in the new version, which triggers `@on_load` again, and this time `:erlang.load_nif` wants to do an upgrade rather than a load. I can work around the problem by patching this into the __init__ generated by Rustler:
```elixir
if __MODULE__ in :erlang.loaded() do
  :ok
else
  :erlang.load_nif(so_path, load_data)
end
```

**Comment by scrogson** [comment]
@pguillory I think you're on the right track. I wonder if it would be potentially better to have the rustler compile task purge the module before, so that it will be recompiled after the new shared object is available?

**Comment by pguillory** [comment]
Yeah, that could work.

FYI the code I pasted above was not a good fix. (Got test failures with `Erlang error: :nif_not_loaded` error. The second `load_nif` call was failing with the upgrade error. So the NIF was loaded but it wasn't connected to the reloaded version of the module.)

**Comment by scohen** [comment]
@scrogson can you repro, or should we submit a patch?

**Comment by scrogson** [comment]
@scohen yes, I have been able to reproduce with the same steps you all have provided. I haven't yet been able to find a legit fix. If you have something, feel free to PR. :+1:

**Comment by scohen** [comment]
@scrogson Can we get a rustler release for this issue?

**Comment by scrogson** [comment]
@scohen unfortunately, I don't have access to `hex`/`cargo` for releases.

@hansihe can we get a new release?

**Comment by scohen** [comment]
@hansihe, can we please have a release? This bug was extremely annoying.

**Comment by hansihe** [comment]
Sorry, I think I missed the last mention.

@scohen Version 0.19.0 released.
