### ISSUE TITLE
Errors when attempting to add Rustler to new project (OTP20, Elixir 1.6.1)

### ISSUE THREAD

**Issue by Qqwy** [hansihe/rustler#130]
Yesterday I attempted to add Rustler to an existing Phoenix project. After following the instructions for version 0.16.0, I obtained the following error, however.

Today I tried to add Rustler to a completely fresh Elixir project, to see if I had misconfigured something, or if there was a conflict happening with other things I was doing.

But on this self-contained Elixir project,whose [source can be found here on GitHub for reference](https://github.com/Qqwy/elixir-broken-rustler-example), exactly the same error occured:

(This is what you see after running `iex -S mix`:)

```elixir
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

==> rustler
Compiling 6 files (.ex)
Generated rustler app
==> elixir_rust_test
Compiling NIF crate :niftest (native/niftest)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Compiling 2 files (.ex)

21:54:55.649 [error] Process #PID<0.188.0> raised an exception
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :bad_name}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    lib/rustler.ex:75: Rustler.compile_config/2
    lib/nif_test.ex:2: NifTest.__init__/0
    (kernel) code_server.erl:1333: anonymous fn/1 in :code_server.handle_on_load/5
 
21:54:55.655 [warn]  The on_load function for module Elixir.NifTest returned:
{%Protocol.UndefinedError{description: "", protocol: String.Chars, value: {:error, :bad_name}}, [{String.Chars, :impl_for!, 1, [file: 'lib/string/chars.ex', line: 3]}, {String.Chars, :to_string, 1, [file: 'lib/string/chars.ex', line: 22]}, {Rustler, :compile_config, 2, [file: 'lib/rustler.ex', ...]}, {NifTest, :__init__, 0, [...]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, ...}]}

Generated elixir_rust_test app
Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)

```

Steps to get here:

1. I started the new elixir project `mix new elixir_rust_test`
2. I added  `{:rustler, "~> 0.16.0"}` to the `mix.exs` dependencies.
3. I ran `mix deps.get`.
4. I ran `mix rustler.new` with as module name `NifTest`.
5. I added a compiler line to the configuration settings of `mix.exs` (line 10): `compilers: [:rustler] ++ Mix.compilers,
6. I added the `rustler_crates` private function to `mix.exs` and refer to it from the `rustler_crates:` setting in the configuration settings function, following the syntax [mentioned here](https://hexdocs.pm/rustler/basics.html), which is the page that the `rustler.new` task refers to once done.
`
7. I created a new module `lib/nif_test.ex` and added the example code that the `rustler.new` task returned in there:
```elixir
defmodule NifTest do
  use Rustler, otp_app: [:elixir_rust_test], crate: "niftest"

  # When your NIF is loaded, it will override this function.
  def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)
end
```
8. I ran `iex -S mix`, which returns in above erroreous output.

**Comment by Qqwy** [comment]
What is going on here? Am I following the setting-up instructions improperly, or is something broken inside Rustler?

**Comment by Qqwy** [comment]
Turns out the mistake was that I wrote `use Rustler, otp_app: [:elixir_rust_test], crate: "niftest"` rather than `use Rustler, otp_app: :elixir_rust_test, crate: "niftest"`.

The reason for this mistake, is that Rustler's example code snippet (shown when the `rustler.new` task is run) returns:
```elixir
defmodule NifTest do
    use Rustler, otp_app: [otp app], crate: "niftest"

    # When your NIF is loaded, it will override this function.
    def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)
end
```
In hindsight, `[otp app]` was meant to be a placeholder, but I interpreted it to be a list of names. I think that just writing `:your_project_name` or something there might be more clear :-).

In any case, I would have never guessed that this was the problem based on the weird errors that were raised, so there probably is something that can be improved in that regard as well. Let me know if you agree; I might be able to contribute with a PR.

Thanks! <3

**Comment by colelawrence** [comment]
Good spot! If you had this problem, another person may as well.

**Comment by mjadczak** [comment]
I did actually have this same problem and it also took me a little time to figure it out.

**Comment by scrogson** [comment]
@Qqwy thanks for pointing out the confusion...we'll make sure to fix that up. :+1:
