### ISSUE TITLE
Feature request: let float decoders fall back to int

### ISSUE THREAD

**Issue by rvlzzr** [hansihe/rustler#132]
I find that any time you want a f64 or f32, getting an integer and converting it to one of these types is perfectly acceptable. For example if you're implementing a sqrt/1 function in elixir with a rust NIF calling the sqrt method on the argument, you probably want sqrt(3) to work the same as sqrt(3.0) rather than raising an exception.

Erlang does this with the functions in its math module -- math:sqrt/1 takes either an int or float for example. I think elixir's Float module is the only place in elixir or erlang that specifically requires a float and raises on an integer.

**Comment by OvermindDL1** [comment]
As long as there is still a way to differentiate.  Performing different actions based on integer or float happens at times.

**Comment by Qqwy** [comment]
I also believe that adding this logic to your decoders is quite straightforward (because decoding stuff returns a Result), and more explicit in what is going on.

**Comment by hansihe** [comment]
This functionality maps directly to the available NIF api functions for decoding numbers. Adding this to rustler would involve attempting to decode once for a float, then once for an integer.

I don't think this functionality belongs in rustler. If anything, it makes more sense to change the NIF API.
