### ISSUE TITLE
Different lazy_static version in template than in rustler

### ISSUE THREAD

**Issue by evnu** [hansihe/rustler#135]
The [Cargo.toml.exs](https://github.com/hansihe/rustler/blob/7e97848c9d4c0592769e326046e9e64d68e984ac/rustler_mix/priv/templates/basic/Cargo.toml.exs#L14) template specifies the use of `lazy_static` with 0.2, but rustler's [Cargo.toml](https://github.com/hansihe/rustler/blob/7e97848c9d4c0592769e326046e9e64d68e984ac/Cargo.toml#L11) uses "0.1.*".  Is this intended?

**Comment by hansihe** [comment]
Nope, this is not intended. We should probably upgrade both to 1.0
