### ISSUE TITLE
Support enif_make_map_from_arrays

### ISSUE THREAD

**Issue by michalmuskala** [hansihe/rustler#157]
This is a new NIF function introduced in OTP 21, which is a more efficient way of building maps than repeated `enif_make_map_put` calls.

Ideally I would imagine rustler to expose a similar primitive with a fallback to the repeated `enif_make_map_put` calls solution, so that libraries can upgrade and take advantage of best performance when running on OTP 21 and have a reasonable fallback on older versions.

Reference: http://erlang.org/doc/man/erl_nif.html#enif_make_map_from_arrays

**Comment by goertzenator** [comment]
This is supported in erlang_nif-sys-0.6.4 but I just notice now that it is not showing up in the documentation for some reason.

[Example from tests](https://github.com/goertzenator/erlang_nif-sys/blob/master/tests/testapp/crates/mynifmod/src/lib.rs#L118)
