### ISSUE TITLE
No released version with OTP 21 support

### ISSUE THREAD

**Issue by mischov** [hansihe/rustler#162]
No version that includes the fix to allow OTP 21 compilation has yet been released- is there a timeline for when this might happen?

I am aware that I can have Mix use pre-released code directly from Github (specific commits, even), but I use Rustler in a library and prefer to limit dependencies to Hex-released packages.

Thank you for your time.

**Comment by scrogson** [comment]
@hansihe ping.

**Comment by hansihe** [comment]
Version 0.18.0 published

**Comment by mischov** [comment]
Thanks Hans!
