### ISSUE TITLE
Cargo doc error when using ResourceArc as parameter

### ISSUE THREAD

**Issue by evnu** [hansihe/rustler#169]
I encountered an error similar to the following when trying to run `cargo doc` against a crate which uses `ResourceArc` as a parameter:

```
error[E0277]: the trait bound `FileResource: rustler::resource::ResourceTypeProvider` is not satisfied
   --> src/lib.rs:124:1
    |
124 | / pub fn debug_cargo_doc(resource: ResourceArc<FileResource>) {
125 | |     println!("this is just fine..");
126 | | }
    | |_^ the trait `rustler::resource::ResourceTypeProvider` is not implemented for `FileResource`
    |
    = note: required by `rustler::resource::ResourceArc`
```

I added an example within [NifIo](https://github.com/evnu/NifIo/commit/7370b38cac5aa71c8070e45bae5008d34750e117). I guess `ResourceArc<T>` should not/cannot be used as a parameter?

**Comment by hansihe** [comment]
I can't seem to reproduce this locally, which rust version are you using when you are hitting the issue?

**Comment by evnu** [comment]
I haven't tried that in a while. I am not sure what Rust version I used back then, something between 1.27-1.30. I will try to reproduce it.

**Comment by evnu** [comment]
I was able to reproduce the above with rust 1.29.0:

```
$ rustup run 1.29.0 cargo doc
$ cd NifIo/native/io
$ # checkout my example
$ rustup run 1.29.0 cargo doc
[...]
error[E0277]: the trait bound `FileResource: rustler::resource::ResourceTypeProvider` is not satisfied
   --> src/lib.rs:124:1
    |
124 | / pub fn debug_cargo_doc(resource: ResourceArc<FileResource>) {
125 | |     println!("this is just fine..");
126 | | }
    | |_^ the trait `rustler::resource::ResourceTypeProvider` is not implemented for `FileResource`
    |
    = note: required by `rustler::resource::ResourceArc`

error: Compilation failed, aborting rustdoc

error: Could not document `io`.
```

I could not reproduce this with 1.30.0 and 1.32.0. Maybe this was a bug in cargo. Feel free to close!
