### ISSUE TITLE
** (Mix) NIF version 2.11 is not supported by Rustler. See https://github.com/hansihe/Rustler/blob/master/FAQ.md#unsuppored-nif-version

### ISSUE THREAD

**Issue by OvermindDL1** [hansihe/Rustler#17]
```bash
$ mix rustler.check
** (Mix) NIF version 2.11 is not supported by Rustler. See https://github.com/hansihe/Rustler/blob/master/FAQ.md#unsuppored-nif-version
```
And yet I have Erlang 19, definitely *not* old by any stretch, although has been out for a while now.

**Comment by goertzenator** [comment]
Ref https://github.com/goertzenator/erlang_nif-sys/issues/15

**Comment by OvermindDL1** [comment]
Ah, waiting on that, no updates to that library in 26 days it seems?

**Comment by goertzenator** [comment]
Today is my github catch-up day.  I'm hoping to wrap that up within a few hours.

**Comment by goertzenator** [comment]
`erlang_nif-sys` now properly supports erlang-19.0 and the 2.11 NIF API.  I assume Rustler now needs a tweak to use this.

**Comment by hansihe** [comment]
Nice work.
Will try to get Rustler updated later on today.

**Comment by hansihe** [comment]
Everything should work on erlang-19 and the 2.11 NIF API now.

@OvermindDL1 Note that the getting started instructions have changed a bit. Since you have the old installer installed, you need to run `mix archive.uninstall rustler_installer.ez` before following the instructions.

**Comment by OvermindDL1** [comment]
Awesome, however to note the uninstall command for me had to be `mix archive.uninstall rustler_installer` without the .ez part.

**Comment by slashmili** [comment]
I just installed the archive and I got the same error.

```
~/d/t/elixir $ mix archive.install https://github.com/hansihe/rustler_archives/raw/master/rustler_installer.ez
Are you sure you want to install archive "https://github.com/hansihe/rustler_archives/raw/master/rustler_installer.ez"? [Yn] y
* creating /Users/milad/.mix/archives/rustler_installer
```

I'm testing on: 
```
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
```

this is the output
```
~/d/t/e/tryout $ mix rustler.check
** (Mix) NIF version 2.11 is not supported by Rustler. See https://github.com/hansihe/Rustler/blob/master/FAQ.md#unsuppored-nif-version
```

**Comment by hansihe** [comment]
Using the mix archive is an outdated method, and you should be using the :rustler mix dependency now. Follow the getting started guide in the readme to get started.

Because you have the mix archive installed, as mentioned above, you need to run `mix archive.uninstall rustler_installer` or `mix archive.uninstall rustler_installer.ex` for the new generator task to work.

**Comment by hansihe** [comment]
I just realized that I forgot to publish the new documentation. I will do that as soon as I can.

**Comment by slashmili** [comment]
Thanks for the update. Sure I'll try the alternative way.

You might as well update this page http://rustler.rustbridge.io/rustler/

**Comment by hansihe** [comment]
Yep, I will do that as soon as I can.

**Comment by hansihe** [comment]
Sorry for taking so long, I have been busy moving the last couple of days.

The documentation is now updated, and should be mostly consistent with the current state of the project.
