### ISSUE TITLE
`rustler_export_nifs` support for multiple Elixir modules

### ISSUE THREAD

**Issue by alinpopa** [hansihe/rustler#173]
Hi,

Is there a limitation on why the `rustler_export_nifs!` is not able to be called with a thing like vector/array of ("Elixir module", array of functions)?
I'm trying to link the functions to multiple Elixir modules, and I wasn't able to find anything that can help me with that, and for a large Rust library, I need to have a single Elixir module with a large number of functions.
Instead of receiving 3 args, to receive a single argument, which is a list of tuples; some pseudo rust syntax for the signature:
```rust
rustler_export_nifs(
    nifs: Vec<(
        String,
        Vec<(String, usize, Identifier, Option<SchedulerFlags>)>,
        Option<fn(env: &Env, load_info: Term) -> bool>
    )>
) {...}
```
If there is no limitation for that, maybe I can come up with a PR that fixes that.

Thanks.

**Comment by scrogson** [comment]
NIF functions are bound to a single erlang/elixir module. Rustler is bound by the Erlang NIF API. `rustler_export_nifs` is the rust equivalent of the `ERL_NIF_INIT` C macro.

Basically you are limited to one module per shared library (the `.so` or `.dll` that is loaded when your erlang module is loaded).

I hope that clears things up.

**Comment by evnu** [comment]
@alinpopa To work around this limitation, you might be able to split the NIF from the Rust library. For example, you want Elixir modules `A` and `B` to expose functions from a crate `c`. Introduce crates `a_nif` and `b_nif`, which have `c` crate as a dependency and provide wrappers to call into the Rust crate. If you can keep `c` "clean" from types which need to link against the Erlang VM, you can then also use all the tools Rust provides to test that crate.

**Comment by alinpopa** [comment]
Thanks @scrogson, it does make sense.

**Comment by alinpopa** [comment]
@evnu I'm glad you said that, as that was my fallback, and validates what I was thinking of doing. Thanks.
