### ISSUE TITLE
Path-based macro imports (Rust 2018)

### ISSUE THREAD

**Issue by evnu** [hansihe/rustler#179]
I tried to use path-based macro imports with Rustler ([example](https://github.com/evnu/NifIo/tree/migrate-to-rust-2018) based on the `NifIo` example), which works with v0.18, but there are two pain points that I want to document here:

* `lazy_static!` must be imported before `rustler_atoms!` (order matters)
* `rustler_atoms!` must be imported before proc-macros such as `NifStruct`

Both pain points are not immediately obvious to resolve. I was able to fix them after reading [this PR](https://github.com/rust-lang-nursery/reference/blob/def43e042cb5348ca70caba4570dd3da1f008728/src/macros-by-example.md#scoping-exporting-and-importing).

Can this be fixed within rustler itself? Maybe [macro hygiene](https://github.com/rust-lang-nursery/reference/blob/def43e042cb5348ca70caba4570dd3da1f008728/src/macros-by-example.md#hygiene) could be of help here. See this comment from that PR:

> Crates written for earlier versions of Rust that use helper macros need to be modified to use $crate or local_inner_macros in order to work well with path-based imports.

Note that this issue here can be closed if there is nothing to be done in Rustler. Maybe an additional section in the README would also be enough.

**Comment by hansihe** [comment]
I gave this a go in 56fd480485cc2eb484c271e993feb6f6423812ab. All macros should now work without `lazy_static`, and proc macros should work as long as `::rustler` is available.

Does this look right to you?

**Comment by evnu** [comment]
> Does this look right to you?

Yes, that looks great, thank you. I tested this by dropping the now useless imports in the [NifIO](https://github.com/evnu/NifIo/commit/6c77f842a9d81752931d822eb9ffb3026dab67a9) example. Now, only imports for macros which are actually referred to are needed.
