### ISSUE TITLE
Attribute to choose between encode and decode for codegen

### ISSUE THREAD

**Issue by evnu** [hansihe/rustler#180]
Sometimes, I'd like to be able to derive an Encoder for a structure, but do not want (or need) a Decoder:

```rust
#[derive(NifStruct, Debug)]
struct MyStruct<'a> {
  some_item: &'a u8
}
```

Currently, `NifStruct ` cannot be derived for such a struct, as we cannot derive a Decoder for a reference (`&'a u8` in this example). It would be nice if it was possible to tell codegen that only encoding or deconding should be implemented. I imagine something like this:

```rust
#[derive(NifStruct, Debug)]
#[rustler(encode)]
struct MyStruct<'a> {
  some_item: &'a u8
}
```

**Comment by evnu** [comment]
@hansihe Are you interested in this? I would be willing to put together a PR.

**Comment by hansihe** [comment]
@evnu Definitely! That would be appreciated

**Comment by evnu** [comment]
Rustler currently uses the `module` and `tag` attribute for deriving Elixir structs / Erlang records. I wonder if it would make sense to allow using those tags in the new attribute as well. Then:

```rust
#[derive(NifStruct, Debug)]
#[rustler(encode, module = "ABC")]
struct MyStruct<'a> {
  some_item: &'a u8
}

// OR support this as well:

#[derive(NifStruct, Debug)]
#[rustler(encode)]
#[rustler(module = "ABC")]
struct MyStruct<'a> {
  some_item: &'a u8
}
```

The current form of `module` and `tag` could be kept for backwards compatibility.
