### ISSUE TITLE
Returning lists

### ISSUE THREAD

**Issue by tmsf** [hansihe/Rustler#19]
As an exercice on rustler, I was trying to create a function fn(list) -> list. It seems this feature is not implemented yet, as I got an error every time I tried to encode a vector.

fn foo<'a>(env: &'a NifEnv, args: &Vec<NifTerm>) -> NifResult<NifTerm<'a>> {
  let iterator: NifListIterator = try!(args[0].decode());

  let result: NifResult<Vec<i64>> = iterator
      .map(|x| x.decode::<i64>())
      .collect::<NifResult<Vec<i64>>>();

  Ok(result.encode(env))
}

Is it possible to add this feature?

**Comment by goertzenator** [comment]
What's the actual error?

**Comment by hansihe** [comment]
We talked about this issue earlier on IRC, I asked him to open a issue about it. No worries.

**Comment by hansihe** [comment]
This is now implemented, see [here](https://github.com/hansihe/Rustler/blob/master/test/src/test_list.rs#L18) for a small example.
