### ISSUE TITLE
Advertise use by Discord

### ISSUE THREAD

**Issue by sanxiyn** [hansihe/rustler#190]
I [learned](https://news.ycombinator.com/item?id=19240040) from Hacker News that Discord is using Rustler. This is just a suggestion, but if you can get a quote from Discord and put it on README, it would be a great marketing for production-readiness of Rustler.

**Comment by scrogson** [comment]
@sanxiyn I think this would be interesting. I will reach out to someone and see if someone would be willing to provide such a quote.

**Comment by sanxiyn** [comment]
I am sure you have seen it, but Discord made an official blog post: https://blog.discordapp.com/using-rust-to-scale-elixir-for-11-million-concurrent-users-c6f19fc029d3.

**Comment by scrogson** [comment]
@sanxiyn - yep. Pretty neat. Thanks for pinging this issue again.
