### ISSUE TITLE
Bug:  Deployed Elixir app breaks due to Rustler trying to link in Mix

### ISSUE THREAD

**Issue by OvermindDL1** [hansihe/Rustler#21]
Mix is only available in a dev environment, not a release environment, and it seems that Rustler is using Mix itself at:  https://github.com/hansihe/Rustler/blob/master/rustler_mix/lib/rustler.ex#L14

This causes the app to fail when deployed.  What should happen is that any generated nif's should be stored in the application-specific priv directory (which you can get via `:code.priv_dir(:application_name)`, thus you might need to have the `load_nif` macro get passed in the application atom as well), then loaded from that directory by getting the private directory path (again via `:code.priv_dir(:whatever_application_name)`).  Mix should never be accessed at any other time other then during compilation.  :-)

**Comment by OvermindDL1** [comment]
Also, the tasks at `lib/task_compile.ex` and `lib/task_new.ex` should really be located at `lib/mix/tasks/compile.rustler.ex` and `lib/mix/tasks/new.ex` respectively.  :-)

**Comment by hansihe** [comment]
I did not think of this, this is definitely a high priority issue.

I will hopefully get to look at this later on today.

**Comment by hansihe** [comment]
Albeit a _little_ late, this should hopefully be fixed by 22fc53e.
