### ISSUE TITLE
rustbridge.io domain registration expired today (Dec 28, 2016)

### ISSUE THREAD

**Issue by svoynow** [hansihe/Rustler#37]
Somebody's probably already on this, but just in case...

**Comment by hansihe** [comment]
I actually didn't know it expired, thanks for the tip

**Comment by hansihe** [comment]
I would prefer to use docs.rs for hosting the docs if I can.

Waiting on https://github.com/onur/docs.rs/issues/23 for that.

**Comment by scrogson** [comment]
Temporary solution would be to host the docs via GitHub pages.

**Comment by hansihe** [comment]
Put docs up at http://hansihe.com/rustler/ for now.
