### ISSUE TITLE
New API for using atoms

### ISSUE THREAD

**Issue by jorendorff** [hansihe/Rustler#56]
Goals

* eliminate the string lookup every time you want to use an atom
* make it easier to remember how to use atoms :)

Maybe users should write this:

    declare_atoms!(ATOMS, [ok, error, ponies]);

and then, whenever they need an atom, simply `ATOMS.ok()` or `ATOMS.ponies().to_term(env)` or whatever.

Kind of unfortunate that the `.to_term(env)` is still necessary :-\

**Comment by jorendorff** [comment]
Also - the current code for atom leaks an environment, `types::atom::ATOM_ENV`.

**Comment by jorendorff** [comment]
@scrogson pointed out that Rust keywords (like `true` and `false`) won't work with this kind of setup.

So here is another possible idea:

```rust
declare_atom_mod!(atoms {ok, ponies, true as true_atom, false as false_atom})
```

To use it, you would say `atoms::ok()`, `atoms::true_atom()`, etc.

**Comment by jorendorff** [comment]
@hansihe Implemented this. The patch adds a bunch of functions `types::atom::{ok, error, badarg, ...}`

I decided on semicolons instead of commas because semicolons are usual for declarations, and trailing is better than separating.  (Supporting an optional trailing comma in a Rust macro is weirdly hard.)

**Comment by hansihe** [comment]
Great work! What do you think about removing the old NIF creation functions? This way seems to be superior in almost every way.

**Comment by jorendorff** [comment]
Taking a look at that now...

**Comment by jorendorff** [comment]
OK, 82f30c8 is my attempt. It replaces the old functions with two new ones. Take a look.

**Comment by jorendorff** [comment]
Two quirks about `rustler_atoms!`:

* If you call it twice in the same scope, you get errors, because all the functions share a cache (by design) and we call it `RUSTLER_ATOMS`. There can't be two things with that name in the same scope.

* The functions it creates are all public. Nothing else in Rust is public by default.

I think these are acceptable. Or, we could change the macro to declare a module of functions, instead of just functions. That would address both issues, but it's a little wordier to use:

```rust
// Current design
rustler_atoms! {
    atom wine;
    atom cheese;
}

// Alternative design
rustler_atoms_mod! {
    mod france_atoms {  // module is private by default
        atom wine;  // seems ok for these to be public by default
        atom cheese;
    }
}
use self::france_atoms::*;
```

**Comment by OvermindDL1** [comment]
Could support both?

**Comment by hansihe** [comment]
Alternatively, atoms could have a `pub` modifier:

```rust
rustler_atoms! {
    pub atom wine;
    pub atom cheese;
}
```
