### ISSUE TITLE
impl Debug for NifTerm

### ISSUE THREAD

**Issue by jorendorff** [hansihe/rustler#59]
This would be a killer feature. I don't see how to implement it, offhand. Especially since a NIF can't call back into Erlang code.

**Comment by jorendorff** [comment]
`erlang_nif-sys` doesn't expose `enif_snprintf` because it takes a variable number of arguments. However, I hacked this into `erlang_nif-sys/lib.rs` and it worked:

    extern "C" {
        pub fn enif_snprintf(str: *mut c_char, size: size_t, format: *const c_char, term: ERL_NIF_TERM) -> c_int;
    }

I think `enif_snprintf` is new in Erlang/OTP 19, which maybe means we should put it behind a feature flag. Everything else works in Erlang/OTP 18 and up.

**Comment by jorendorff** [comment]
See 7ca1e09.

**Comment by scrogson** [comment]
Could this be something we could only make available when using in `debug` mode? If you attempt to use in `release` mode it would not compile?

**Comment by hansihe** [comment]
No, the debug trait simply describes what happens when you try to debug print something. I don't think there is any reason this should only be available in release mode.

**Comment by scrogson** [comment]
@hansihe I think you misunderstood me? I was saying that the Debug trait impl should only be available if the crate is compiled in `debug` (default) mode. If the crate is compiled in `release` mode, any debug formatting left in could throw a compile error.

I'm not even sure this is possible or a good idea, just throwing it out there.

But also putting it behind a feature could be a nice way to make it optional.

**Comment by hansihe** [comment]
Seeing as no other debug implementations do this, I don't think we should do it either.

**Comment by jorendorff** [comment]
I just found out that Rust *does* support varargs for extern "C" functions. So this will be pretty easy, it starts with uncommenting a few lines in `erlang_nif-sys`.

**Comment by jorendorff** [comment]
https://github.com/goertzenator/erlang_nif-sys/pull/23

**Comment by hansihe** [comment]
This was resolved a while ago.
