### ISSUE TITLE
Leading slash in relative path

### ISSUE THREAD

**Issue by NobbZ** [hansihe/Rustler#66]
In the [documentation](https://hexdocs.pm/rustler/basics.html#crate-configuration) there is written:

> - `path` - The path to the crate directory relative to the project root.

But when do use something that looks like a relative path (eg. `native/foo`), compiliation fails with a message like the following:

> ```
> Compiling NIF crate :foo (native/foo)...
> Directory '/home/nobbz/projects/elixir/projectnative/foo' could not be found.
> One of the crate directories specified for compilation does not exist.
> ```

If I do prepend that with a slash, then compilation works, but `/native/foo` looks like an absolute path.

**Comment by hansihe** [comment]
This should be fixed in 351ac7fb5b6ed9759dd6697eca2bb9e4f291195a.
