### ISSUE TITLE
versions out of sync

### ISSUE THREAD

**Issue by NobbZ** [hansihe/Rustler#67]
After I created a new Nif-module using rustler_mix 0.5.0, I do get a `Cargo.toml` referencing the following dependencies:

* rustler = "0.12.0"
* rustler_codegen = "0.12.0"

But both of them are only available as 0.11.0 on crates.io.

**Comment by hansihe** [comment]
We know this, and we should probably add a note about it somewhere. Use versions from git for now.

Closing in favor of issue #26.
