### ISSUE TITLE
Generated stubs create type-mismatch

### ISSUE THREAD

**Issue by NobbZ** [hansihe/Rustler#68]
After I was able to circumvent other problems, already reported here (#66, #67) I do now get the errors below. I have not touched the generated stubs.

> ```
> Compiling NIF crate :spacecolony_nif (native/spacecolony_nif)...
>    Compiling spacecolony_nif v0.1.0 (file:///home/nobbz/projects/elixir/space_colony/native/spacecolony_nif)
> error[E0308]: mismatched types
>  --> /home/nobbz/projects/elixir/space_colony/_build/dev/rustler_crates/spacecolony_nif/debug/build/spacecolony_nif-ecbe9ff9de559671/out/lib.rs:9:29
>   |
> 9 |     Ok((num1 + num2).encode(env))
>   |                             ^^^ expected struct `rustler::NifEnv`, found reference
>   |
>   = note: expected type `rustler::NifEnv<'_>`
>   = note:    found type `&'a rustler::NifEnv<'_>`
> 
> error[E0308]: mismatched types
>   --> src/lib.rs:15:1
>    |
> 15 | include!(concat!(env!("OUT_DIR"), "/lib.rs"));
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rustler::NifEnv`, found reference
>    |
>    = note: expected type `fn(rustler::NifEnv<'a>, &std::vec::Vec<rustler::NifTerm<'a>>) -> std::result::Result<rustler::NifTerm<'a>, rustler::NifError>`
>    = note:    found type `fn(&'a rustler::NifEnv<'_>, &std::vec::Vec<rustler::NifTerm<'_>>) -> std::result::Result<rustler::NifTerm<'a>, rustler::NifError> {add}`
>    = note: this error originates in a macro outside of the current crate
> 
> error: aborting due to 2 previous errors
> ```

**Comment by hansihe** [comment]
We are in the middle of some really big changes, and I usually update the templates before a release.

If you want to use the generator, I can update it for you now.

**Comment by NobbZ** [comment]
It should be enough if you could provide a working example in the README
and rustdoc. That is usually my next stop after generated files don't work.

Hans Elias J. <notifications@github.com> schrieb am So., 15. Jan. 2017 um
17:31 Uhr:

**Comment by scrogson** [comment]
I have some work in progress to update the templates.

**Comment by NobbZ** [comment]
May I ask on which branch they reside @scrogson?

**Comment by scrogson** [comment]
It's not published yet. I can push it up as soon as I get on my computer.
I'll post back here to let you know.

**Comment by scrogson** [comment]
@NobbZ the PR is here: https://github.com/hansihe/Rustler/pull/69

**Comment by NobbZ** [comment]
Thank you! that was enough for me to get me up and running.
