### ISSUE TITLE
Consider changing name to erlust

### ISSUE THREAD

**Issue by alizain** [hansihe/rustler#82]
Totally side and random feedback, but you might like `erlust` more than `rustler`, where `erlust` is comprised of **erl**ang and r**ust**

**Comment by hansihe** [comment]
I do think `erlust` is a really good name, possibly even more than `rustler`. However, I feel like changing the name at this point would serve no other real purpose other than being an annoyance. A name change will probably not happen.

Thanks for the name suggestion though :)

**Comment by alizain** [comment]
Completely agree :)
