### ISSUE TITLE
Tuple support?

### ISSUE THREAD

**Issue by walkr** [hansihe/rustler#86]
Hello,

I'm trying to create a function in rust which takes two tuples, but it fails.

```rust
#[macro_use] extern crate rustler;
#[macro_use] extern crate rustler_codegen;
#[macro_use] extern crate lazy_static;
#[macro_use] extern crate geo;

use rustler::{NifEnv, NifTuple, NifTerm, NifResult, NifEncoder};

#[derive(NifTuple)]
struct PointTuple {
    lat: f64,
    long: f64,
}

fn centroid<'a>(env: NifEnv<'a>, args: &[NifTerm<'a>]) -> NifResult<NifTerm<'a>> {

    // println!("{:&}", args);
    let p1: PointTuple = try!(args[0].decode());
    let p2: PointTuple = try!(args[1].decode());

   ...
```

Error message:

```shell
error: custom derive attribute panicked
  --> src/lib.rs:26:10
   |
26 | #[derive(NifTuple)]
   |          ^^^^^^^^
   |
   = help: message: assertion failed: !p.is_null()
```

If I also run `mix test` inside `rustler/test` I get the same error.
```shell
error: custom derive attribute panicked
 --> src/test_codegen.rs:4:10
  |
4 | #[derive(NifTuple)]
  |          ^^^^^^^^
  |
  = help: message: assertion failed: !p.is_null()

error: Could not compile `rustler_test`.
```

Its there a way to handle tuples as arguments in functions?
Thank you!

**Comment by hansihe** [comment]
That's strange, the procedural macro shouldn't panic.

Could you try again while using `rustler_codegen` from master? You only need to change the `rustler_codegen` dependency to something like `rustler_codegen = { git = "git@github.com:hansihe/rustler.git" }`.

If you would like an alternative solution, you could encode the tuples directly, as tuples up to length 7 implement NifEncoder and NifDecoder.

```rust
let (p1_lat, p1_long): (f32, f32) = args[0].decode();
```

**Comment by walkr** [comment]
```rust
let (p1_lat, p1_long): (f32, f32) = args[0].decode();
```

Yeah,

That's what I've actually ended up doing.

Unfortunately, the test project still fails with the same error, even when specifying the cargo dependency to point to master.

I'm using rustc 1.15.1 btw.

Cheers!
