### ISSUE TITLE
compiling rustler-0.13.0 failed

### ISSUE THREAD

**Issue by rivercheng** [hansihe/rustler#88]
error[E0308]: mismatched types
   --> /home/chengwei/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler-0.13.0/src/wrapper/nif_interface.rs:178:68
    |
178 |     erlang_nif_sys::enif_open_resource_type(env, module_str, name, dtor, flags, tried)
    |                                                                    ^^^^ expected unsafe fn, found normal fn
    |
    = note: expected type `std::option::Option<unsafe extern "C" fn(*mut wrapper::nif_interface::erlang_nif_sys::ErlNifEnv, *mut std::os::raw::c_void)>`
    = note:    found type `std::option::Option<extern "C" fn(*mut wrapper::nif_interface::erlang_nif_sys::ErlNifEnv, *mut std::os::raw::c_void)>`

error[E0308]: mismatched types
   --> /home/chengwei/.cargo/registry/src/github.com-1ecc6299db9ec823/rustler-0.13.0/src/wrapper/nif_interface.rs:226:61
    |
226 |     erlang_nif_sys::enif_schedule_nif(env, fun_name, flags, dtor, argc, argv)
    |                                                             ^^^^ expected unsafe fn, found normal fn
    |
    = note: expected type `std::option::Option<unsafe extern "C" fn(*mut wrapper::nif_interface::erlang_nif_sys::ErlNifEnv, i32, *const usize)>`
    = note:    found type `std::option::Option<extern "C" fn(*mut wrapper::nif_interface::erlang_nif_sys::ErlNifEnv, i32, *const usize)>`

error: aborting due to 2 previous errors

**Comment by jorendorff** [comment]
80a2671 fixes this. I guess it could be worth a 0.13.1 release. (?)

**Comment by jorendorff** [comment]
@rivercheng, What Rust version are you using? `rustc --version` says 1.15.0 for me, and it builds OK.

**Comment by hansihe** [comment]
It's worth noting that this error will only happen if you have a cargo.lock from after the new erlang_nif-sys version.

This is probably well worth a new release, I will try to get it done later today.

**Comment by hansihe** [comment]
Published a new version 0.14.0. The reason I didn't publish 0.13.1 is because this release contains improvements in addition to bugfixes.
