### ISSUE TITLE
Could not find `erlang_nif_sys` in `wrapper::nif_interface`

### ISSUE THREAD

**Issue by ZGF4** [hansihe/rustler#89]
When I try to compile rustler I get a bunch of errors all saying
> Could not find `erlang_nif_sys` in `wrapper::nif_interface`

**Comment by hansihe** [comment]
That's very strange.

Could you post one of the full errors you are getting?

What version of Rust are you using?

**Comment by kprieb** [comment]
I think this just got fixed.

**Comment by hansihe** [comment]
Closing this. Will reopen if someone else has the same problem.
