### ISSUE TITLE
Suggested Readme improvements and guide for Phoenix integration

### ISSUE THREAD

**Issue by cgregfreeman** [hansihe/rustler#92]
My environment is Linux Mint 17.3 (Trusty Tahr) with version 19.3 of Erlang/OTP, Elixir 1.4.2, Rustc 1.17.0.

I noticed a few inconsistences with the guide and readme and here is how I resolved them:

The README.md generated with the rustler.new command has the following code:

```Elixir
defmodule ModuleName
require Rustler

@on_load :load_nif
def load_nif do
    Rustler.load_nif("projectname")
end
...
end
```

This code throws an Elixir error as-is.  The code at https://hexdocs.pm/rustler/basics.html does not match this autogenerated README. Neither of them work as-is.

> == Compilation error on file lib/module_name.ex ==
** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

After some experimentation, here's what I got to work:

```Elixir
defmodule ModuleName
    use Rustler, otp_app: :appName, crate: :cratename

    :load_nif  #Removed @on_load, but including :load_nif is important! Causes a segfault indeterminantly!
    def load_nif do
        Rustler.load_nif("nifname")
    end

    # When your NIF is loaded, it will override this function.
    def add(_a, _b), do: throw :nif_not_loaded
end
```

As noted in the comment above, I got a really strange segmentation fault when I ran this without the :load_nif code with Phoenix. It worked, consistently, in an elixir/mix project outside of Phoenix, but as soon as I had the exact same source in the /native/ directory of my Phoenix project, it would sometimes segfault and sometimes run. I could enter iex -S mix, get it to run, exit, then re-run iex -S mix, and then it would segmentation fault. 

As for a guide on including with Phoenix:

This may not be obvious for some people, but there is already a "compilers:" block in the project function. Including an additional compilers block, like I did because I didn't know any better, results in Rustler and Phoenix looking in the _build/dev/lib/project/priv directory and being unable to find the Rust crates.
```Elixir
def project do
compilers: [:rustler, :phoenix, :gettext ] ++ Mix.compilers, #<---- How important is the order here?!
rustler_crates: rustler_crates() #<--- does this position matter?
```
I don't think the order matters here but I could be wrong. It would be clear to explicitly state that.
While trying to figure out my problem I played around with the ordering some and I'm not convinced that the ordering of the atoms and the listing of the crates doesn't matter yet.

I hope this is helpful as this is a great project and I see lots of potential with Rust + Phoenix.

**Comment by hansihe** [comment]
Thanks for the feedback!

I will update the documentation to make some of these things more clear.

I am really curious about the segfault you are getting. This is not something that should happen, and I would be very interested in figuring out what is going on here.

**Comment by cgregfreeman** [comment]
I went through and tried to replicate the segfault but I was not able to with a clean install. If I find it again I will narrow it down to a particular issue now that I know how to get everything working.

I also created a tutorial on how to get rustler up and running with phoenix here: https://github.com/cgregfreeman/phoenix_rustler_integration
Feel free to copy and edit or use as needed.

**Comment by hansihe** [comment]
I changed the documentation around a bit in the generated README.

**Comment by korczis** [comment]
I implemented working example here - https://github.com/korczis/rustler-test
