### ISSUE TITLE
Encoding and decoding Elixir structs

### ISSUE THREAD

**Issue by alex-shapiro** [hansihe/rustler#97]
The compiler plugin `ExStruct` for [encoding and decoding Elixir structs](https://docs.rs/rustler/0.14.0/rustler/types/elixir_struct/index.html) looks like it no longer exists in the codebase (except in an unused [test file](https://github.com/hansihe/rustler/blob/master/rustler_codegen/test.rs#L1997) in codegen). How easy would it be to modify `NifMap` to create a derive-able`NifStruct` macro? I'm imagining something like this:

```rust
#[derive(NifStruct(module = "MyStruct"))]
pub struct MyStruct {
    id: i32,
    name: String,
}
```

I've never written a derive-able macro before so I don't know how much effort this would take.

**Comment by hansihe** [comment]
Fixed by #98
